# Generated by Django 4.2.10 on 2024-02-12 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter an ingredient name (e.g. Simple Syrup)', max_length=100, unique=True)),
            ],
        ),
    ]
