# Generated by Django 4.2.10 on 2024-02-12 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredient',
            name='id',
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='name',
            field=models.CharField(help_text='Enter an ingredient name (e.g. Simple Syrup)', max_length=100, primary_key=True, serialize=False),
        ),
    ]
