# Generated by Django 4.2.10 on 2024-02-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0002_remove_ingredient_id_alter_ingredient_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecipeSource',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('url', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
