# Generated by Django 4.2.10 on 2024-02-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0003_recipesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSource',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
