# Generated by Django 4.2.10 on 2024-02-12 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0004_imagesource'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('slug', models.SlugField(default='')),
                ('recipe_url', models.URLField(blank=True, null=True)),
                ('ingredients', models.ManyToManyField(help_text='Select the ingredients for this drink', to='drinks.ingredient')),
                ('recipe_source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='drinks.recipesource')),
            ],
        ),
    ]
