# Generated by Django 4.2.10 on 2024-02-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0005_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('number', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, unique=True)),
                ('date', models.DateField(unique=True)),
                ('url', models.URLField(default='https://play.acast.com/s/thesloppyboys/')),
                ('instagram_post_url', models.URLField(blank=True, null=True)),
                ('twitter_post_url', models.URLField(blank=True, null=True)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.drink')),
            ],
        ),
    ]
