# Generated by Django 4.2.10 on 2024-02-13 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0006_episode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=200, unique=True, upload_to='images')),
                ('recipe', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.drink')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.imagesource')),
            ],
        ),
    ]
