# Generated by Django 4.2.10 on 2024-02-17 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0008_alter_image_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='image',
        ),
        migrations.AddField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=240, null=True),
        ),
    ]
