# Generated by Django 4.2.10 on 2024-02-17 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0009_remove_image_image_image_filename'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
