# Generated by Django 4.2.10 on 2024-02-17 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0010_delete_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=240)),
                ('recipe', models.BooleanField(default=False)),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.drink')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='drinks.imagesource')),
            ],
        ),
    ]
