# Generated by Django 4.2.10 on 2024-02-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drinks', '0011_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='filename',
            field=models.CharField(max_length=240, primary_key=True, serialize=False),
        ),
    ]
